server:
  port: 8080
spring:
  config:
    import: "application-secret.yml"
  datasource:
    url: jdbc:mysql://localhost:3306/food
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update